ignore:
  - "Sources/Authenticator/Views"
  - "Sources/Authenticator/Theming"
  - "Sources/Authenticator/Authenticator.swift"

codecov:
  branch: main

coverage:
  status:
    project:
      default:
        threshold: 1%
